-- Healthcare dashboard record tables
-- Creates: hc_call_logs, hc_pms_records, hc_calibration_records, hc_training_records, hc_rber_records

CREATE TABLE IF NOT EXISTS hc_call_logs (
  id              INT UNSIGNED     NOT NULL AUTO_INCREMENT,
  company_id      INT UNSIGNED     NOT NULL,
  asset_id        INT UNSIGNED     NULL,
  asset_name      VARCHAR(200)     NULL,
  department_id   INT UNSIGNED     NULL,
  location        VARCHAR(255)     NULL,
  call_date       DATE             NOT NULL,
  call_time       TIME             NULL,
  caller_name     VARCHAR(160)     NULL,
  caller_contact  VARCHAR(64)      NULL,
  issue_reported  TEXT             NULL,
  call_type       VARCHAR(80)      NULL,
  priority        ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  status          VARCHAR(40)      NOT NULL DEFAULT 'open',
  created_by      INT UNSIGNED     NULL,
  created_at      TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_hc_call_logs_company    (company_id),
  KEY idx_hc_call_logs_date       (call_date),
  KEY idx_hc_call_logs_department (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hc_pms_records (
  id               INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  company_id       INT UNSIGNED  NOT NULL,
  asset_id         INT UNSIGNED  NULL,
  asset_name       VARCHAR(200)  NULL,
  department_id    INT UNSIGNED  NULL,
  location         VARCHAR(255)  NULL,
  scheduled_date   DATE          NOT NULL,
  completed_date   DATE          NULL,
  maintenance_type VARCHAR(100)  NULL,
  frequency        VARCHAR(80)   NULL,
  technician_name  VARCHAR(160)  NULL,
  technician_id    INT UNSIGNED  NULL,
  checklist_used   VARCHAR(200)  NULL,
  findings         TEXT          NULL,
  action_taken     TEXT          NULL,
  next_due_date    DATE          NULL,
  status           VARCHAR(40)   NOT NULL DEFAULT 'scheduled',
  cost             DECIMAL(12,2) NULL,
  remarks          TEXT          NULL,
  created_by       INT UNSIGNED  NULL,
  created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_hc_pms_company    (company_id),
  KEY idx_hc_pms_date       (scheduled_date),
  KEY idx_hc_pms_department (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hc_calibration_records (
  id                  INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  company_id          INT UNSIGNED  NOT NULL,
  asset_id            INT UNSIGNED  NULL,
  asset_name          VARCHAR(200)  NULL,
  department_id       INT UNSIGNED  NULL,
  location            VARCHAR(255)  NULL,
  calibration_date    DATE          NOT NULL,
  next_due_date       DATE          NULL,
  calibrated_by       VARCHAR(160)  NULL,
  lab_name            VARCHAR(200)  NULL,
  certificate_no      VARCHAR(120)  NULL,
  calibration_result  VARCHAR(40)   NOT NULL DEFAULT 'Pass',
  deviation           VARCHAR(120)  NULL,
  standard_used       VARCHAR(200)  NULL,
  remarks             TEXT          NULL,
  status              VARCHAR(40)   NOT NULL DEFAULT 'valid',
  created_by          INT UNSIGNED  NULL,
  created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_hc_cal_company    (company_id),
  KEY idx_hc_cal_date       (calibration_date),
  KEY idx_hc_cal_department (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hc_training_records (
  id             INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  company_id     INT UNSIGNED  NOT NULL,
  asset_id       INT UNSIGNED  NULL,
  asset_name     VARCHAR(200)  NULL,
  department_id  INT UNSIGNED  NULL,
  employee_id    INT UNSIGNED  NULL,
  employee_name  VARCHAR(160)  NULL,
  training_title VARCHAR(200)  NOT NULL,
  training_type  VARCHAR(100)  NULL,
  trainer_name   VARCHAR(160)  NULL,
  training_date  DATE          NOT NULL,
  expiry_date    DATE          NULL,
  score          DECIMAL(5,2)  NULL,
  result         VARCHAR(40)   NOT NULL DEFAULT 'Pass',
  certificate_no VARCHAR(120)  NULL,
  remarks        TEXT          NULL,
  created_by     INT UNSIGNED  NULL,
  created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_hc_training_company    (company_id),
  KEY idx_hc_training_date       (training_date),
  KEY idx_hc_training_department (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hc_rber_records (
  id                    INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  company_id            INT UNSIGNED  NOT NULL,
  asset_id              INT UNSIGNED  NULL,
  asset_name            VARCHAR(200)  NULL,
  department_id         INT UNSIGNED  NULL,
  location              VARCHAR(255)  NULL,
  review_date           DATE          NOT NULL,
  next_review_date      DATE          NULL,
  reviewer_name         VARCHAR(160)  NULL,
  reviewer_id           INT UNSIGNED  NULL,
  risk_score            DECIMAL(5,2)  NULL,
  risk_level            VARCHAR(40)   NOT NULL DEFAULT 'Medium',
  equipment_function    TEXT          NULL,
  failure_consequences  TEXT          NULL,
  maintenance_strategy  TEXT          NULL,
  recommended_interval  VARCHAR(80)   NULL,
  action_required       TEXT          NULL,
  status                VARCHAR(40)   NOT NULL DEFAULT 'pending',
  remarks               TEXT          NULL,
  created_by            INT UNSIGNED  NULL,
  created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_hc_rber_company    (company_id),
  KEY idx_hc_rber_date       (review_date),
  KEY idx_hc_rber_department (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
